import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../public/imagem.png'
import styles from '../styles/Home.module.css'
import pictures from "../public/fundoefeito.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JobsNet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <a className={styles.fundoefeito}>
          <Image src={pictures} alt="rsrsrs" />
        </a>

        <a className={styles.imageminicial}>
          <Image src={profilePic} alt="Picture of the author" />
        </a>

        <h1 className={styles.title}>
          Encontre novas vagas todos os dias.
        </h1>
        <p1 className={styles.subtitlehome}>Conquiste seu emprego dos sonhos</p1>

        <div className={styles.grid}>
          <a className={styles.card}>
            <ul className= {styles.home}>
              <a>Home</a>
            </ul>
            <ul className={styles.vagas}>
              <a>Vagas</a>
            </ul>

            <ul className={styles.quemsomos}>
              <a>Quem somos</a>
            </ul>

            <ul className ={styles.meuperfil}>
              <a>Meu perfil</a>
            </ul>
          </a>

          <a>

          <ul className ={styles.botaoCadastro}>
          <a>Cadastrar-se</a>
          </ul>

          </a>

        </div>
      </main>
    
    <div className={styles.forms}>

    <form name="contact" method="POST" data-netlify="true">
      <p className = {styles.name}>
        <label htmlFor="name">Name</label>
        <input type="text" id="name" name="name" />
      </p>
      <p>
        <label htmlFor="email">Email</label>
        <input type="text" id="email" name="email" />
      </p>
      <p>
        <label htmlFor="message">Message</label>
        <textarea id="message" name="message"></textarea>
      </p>
      <p>
        <button type="submit">Send</button>
      </p>

    </form>

    </div>

</div>
  )
}
